name: Android-Cloud
on: workflow_dispatch
jobs:
  run-vps:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Start Cloud Android
        run: |
          # এখানে আমরা একটি হালকা অ্যান্ড্রয়েড সিস্টেম ব্যবহার করছি
          docker run -d -p 5900:5900 --privileged accetto/ubuntu-vnc-xfce-chromium-g3
          sleep 15
          echo "লিঙ্কটি এখানে পাবেন:"
          curl --silent http://127.0.0.1:4040/api/tunnels | jq -r '.tunnels[0].public_url'
          ngrok tcp 5900
          
